# This is a basic workflow to help you get started with Actions

name: apigee-deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**.md'

jobs:
  apigee_deployment_job:
    runs-on: ubuntu-latest
    name: Deploy Apigee Proxy
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    
    - name: Deployment
      id: deployment
      uses: g-lalevee/apigeetool-deployment-action@master
      with:
        APIGEETOOL_ERROR_STOP: false
        APIGEE_USERNAME: ${{ secrets.APIGEE_ID }}
        APIGEE_PASSWORD: ${{ secrets.APIGEE_PWD }}
          
    # Use the output from the `Deployment` step
    - name: Get the Apigeetool Return Code
      run: echo "Apigeetool ended with code ${{ steps.deployment.outputs.RC }}"

    # Edit Newman environment file from .env file
    # Newman environment file must contains <hostname> value
    # It will be replace by Apigee target hostname = organization-environment.apigee.net 
    - name: Update Newman environment file
      run: ./test/update-target.sh

    - name: Unit Test
      id: test
      uses: g-lalevee/newman-test-action@master
      with:
        collection: test/petstore.postman_collection.json
        environment: test/postman_environment.json
        iterationCount: 2
        workingDir: test

